
document.write('  <div class="optionbox">');
document.write('  <h2><input type="radio" name="searchtype" value="colloc4nlg" checked /> Collocations for NLG</h2>');
document.write('  ');
document.write('  <p>');
document.write('    <strong>Collocation scores</strong>:');
document.write('    &nbsp;<input type="checkbox" name="mistat" />Mutual Information &nbsp;');
document.write('    &nbsp;<input type="checkbox" name="dstat" />Dice &nbsp;');
document.write('    &nbsp;<input type="checkbox" name="tstat" />T-score &nbsp;');
document.write('    &nbsp;<input type="checkbox" name="llstat" checked /> Loglikelihood score');
document.write('  </p>');
document.write('  <p>');
document.write('    <strong>Context</strong>:<br>');
document.write('    &nbsp;PoS<INPUT name=cfilter1 value="NN" size=3>  <input type="input" name="cleft1" size="2" value="0" /> w left <input type="input" name="cright1" size="2" value="2" /> w right<br>');
document.write('    &nbsp;PoS<INPUT name=cfilter2 value="JJ" size=3>  <input type="input" name="cleft2" size="2" value="2" /> w left <input type="input" name="cright2" size="2" value="0" /> w right<br>');
document.write('    &nbsp;<strong>keyword</strong><br>');
document.write('    &nbsp;PoS<INPUT name=cfilter3 size=3>  <input type="input" name="cleft3" size="2" value="0" /> w left <input type="input" name="cright3" size="2" value="0" /> w right<br>');
document.write('    &nbsp;PoS<INPUT name=cfilter4 size=3>  <input type="input" name="cleft4" size="2" value="0" /> w left <input type="input" name="cright4" size="2" value="0" /> w right<br>');
document.write('    <input type="hidden" name="cleft" value="0" />');
document.write('    <input type="hidden" name="cright" value="0" />');
document.write('  </p>');
document.write('  <p>');
document.write('    <br>');
document.write('  </p>');
document.write('');
document.write('  </div>');
document.write('');
document.write('<div class="optionbox">');
document.write('<h2><input type="radio" name="searchtype" value="conc" /> Concordance</h2>');
document.write('  <p>');
document.write('    <strong>Context</strong>:&nbsp;<input type="text" name="contextsize" size="3" value="60c" /> (c for characters, w for words)<br />');
document.write('    <br />');
document.write('    <strong>Sort by</strong>:');
document.write('    &nbsp;<input type="radio" name="sort1" value="document" />Document');
document.write('    &nbsp;<input type="radio" name="sort1" value="fq" />Frequency');
document.write('    &nbsp;<input type="radio" name="sort1" value="lemma" />lemma');
document.write('    &nbsp;<input type="radio" name="sort1" value="word" checked />word<br />');
document.write('    Then by:');
document.write('    &nbsp;<input type="radio" name="sort2" value="left" />left');
document.write('    &nbsp;<input type="radio" name="sort2" value="right" checked />right<br />');
document.write('  </p>');
document.write('<strong>Output</strong>: <INPUT name=terminate size=4 value="100"> lines');
document.write('  </div>');
document.write('');
document.write('  <div class="optionbox">');
document.write('  <h2><input type="radio" name="searchtype" value="colloc"/> Collocations</h2>');
document.write('  ');
document.write('  <p>');
document.write('    <strong>Collocation scores</strong>:');
document.write('    &nbsp;<input type="checkbox" name="mistat" />Mutual Information &nbsp;');
document.write('    &nbsp;<input type="checkbox" name="dstat" />Dice &nbsp;');
document.write('    &nbsp;<input type="checkbox" name="tstat" />T-score &nbsp;');
document.write('    &nbsp;<input type="checkbox" name="llstat" checked /> Loglikelihood score');
document.write('  </p>');
document.write('  <p>');
document.write('    <strong>Context</strong>:');
document.write('    &nbsp;<input type="input" name="cleft" size="2" value="0" /> words on the left ');
document.write('    &nbsp;<input type="input" name="cright" size="2" value="1" /> words on the right');
document.write('  </p>');
document.write('  <p>');
document.write('    <strong>POS tag of the collocate</strong>:&nbsp;<INPUT name=cfilter size=3> POS tags<br>');
document.write('  </p>');
document.write('');
document.write('  </div>');
